import { DashboardWidgetConfig } from './dashboard-widget-config.model';

export const WIDGET_REGISTRY: DashboardWidgetConfig[] = [
  {
    id: 'todays-tasks',
    title: "Today's Tasks",
    icon: 'task_alt',
    component: 'todays-tasks',
    defaultX: 0,
    defaultY: 0,
    defaultW: 12,
    defaultH: 3,
    minW: 6,
    minH: 2,
  },
  {
    id: 'jobs-by-stage',
    title: 'Jobs by Stage',
    icon: 'bar_chart',
    component: 'jobs-by-stage',
    defaultX: 0,
    defaultY: 3,
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  {
    id: 'team-load',
    title: 'Team Load',
    icon: 'groups',
    component: 'team-load',
    defaultX: 6,
    defaultY: 3,
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  {
    id: 'activity',
    title: 'Activity',
    icon: 'history',
    component: 'activity',
    defaultX: 0,
    defaultY: 7,
    defaultW: 8,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  {
    id: 'deadlines',
    title: 'Deadlines',
    icon: 'event',
    component: 'deadlines',
    defaultX: 8,
    defaultY: 7,
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 3,
  },
  {
    id: 'cycle-progress',
    title: 'Cycle Progress',
    icon: 'loop',
    component: 'cycle-progress',
    defaultX: 0,
    defaultY: 11,
    defaultW: 4,
    defaultH: 3,
    minW: 3,
    minH: 2,
  },
  {
    id: 'open-orders',
    title: 'Open Orders',
    icon: 'shopping_cart',
    component: 'open-orders',
    defaultX: 4,
    defaultY: 11,
    defaultW: 4,
    defaultH: 3,
    minW: 3,
    minH: 2,
  },
  {
    id: 'eod-prompt',
    title: 'End of Day',
    icon: 'nightlight',
    component: 'eod-prompt',
    defaultX: 8,
    defaultY: 11,
    defaultW: 4,
    defaultH: 3,
    minW: 3,
    minH: 2,
  },
  {
    id: 'margin-summary',
    title: 'Margin Summary',
    icon: 'trending_up',
    component: 'margin-summary',
    defaultX: 0,
    defaultY: 14,
    defaultW: 6,
    defaultH: 3,
    minW: 4,
    minH: 2,
  },
];
