export type ReportType =
  | 'jobs-by-stage'
  | 'overdue-jobs'
  | 'time-by-user'
  | 'expense-summary'
  | 'lead-pipeline'
  | 'job-completion-trend'
  | 'on-time-delivery'
  | 'average-lead-time'
  | 'team-workload'
  | 'customer-activity'
  | 'my-work-history'
  | 'my-time-log'
  | 'ar-aging'
  | 'revenue'
  | 'simple-pnl';
