using Bogus;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;
using QBEngineer.Api.Features.Parts;
using QBEngineer.Core.Entities;
using QBEngineer.Core.Enums;
using QBEngineer.Core.Interfaces;
using QBEngineer.Core.Models;

namespace QBEngineer.Tests.Handlers.Parts;

public class CreatePartHandlerTests
{
    private readonly Mock<IPartRepository> _partRepo = new();
    private readonly CreatePartHandler _handler;

    private readonly Faker _faker = new();

    public CreatePartHandlerTests()
    {
        _handler = new CreatePartHandler(
            _partRepo.Object,
            Mock.Of<ISyncQueueRepository>(),
            Mock.Of<IAccountingProviderFactory>(),
            Mock.Of<IBarcodeService>(),
            Mock.Of<ILogger<CreatePartHandler>>());
    }

    [Fact]
    public async Task Handle_ValidCommand_CreatesPartWithAutoGeneratedNumber()
    {
        // Arrange
        var description = _faker.Commerce.ProductName();
        var material = _faker.Commerce.ProductMaterial();

        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Part, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        var expectedResult = new PartDetailResponseModel(
            1, "PRT-00001", description, "A", PartStatus.Draft, PartType.Part,
            material, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            new List<BOMEntryResponseModel>(), new List<BOMUsageResponseModel>(),
            DateTime.UtcNow, DateTime.UtcNow);

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(expectedResult);

        var command = new CreatePartCommand(description, null, PartType.Part, material, null, null);

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.PartNumber.Should().Be("PRT-00001");

        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.PartNumber == "PRT-00001" &&
            p.Description == description.Trim() &&
            p.Revision == "A" &&
            p.Status == PartStatus.Draft &&
            p.PartType == PartType.Part &&
            p.Material == material.Trim()
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_NoRevision_DefaultsToA()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Part, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        var expectedResult = new PartDetailResponseModel(
            1, "PRT-00001", "Test Part", "A", PartStatus.Draft, PartType.Part,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            new List<BOMEntryResponseModel>(), new List<BOMUsageResponseModel>(),
            DateTime.UtcNow, DateTime.UtcNow);

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(expectedResult);

        var command = new CreatePartCommand("Test Part", null, PartType.Part, null, null, null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Revision == "A"
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_WithRevision_UsesProvidedRevision()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Assembly, It.IsAny<CancellationToken>()))
            .ReturnsAsync("ASM-00001");

        var expectedResult = new PartDetailResponseModel(
            1, "ASM-00001", "Test Part", "C", PartStatus.Draft, PartType.Assembly,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            new List<BOMEntryResponseModel>(), new List<BOMUsageResponseModel>(),
            DateTime.UtcNow, DateTime.UtcNow);

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(expectedResult);

        var command = new CreatePartCommand("Test Part", "C", PartType.Assembly, null, null, null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Revision == "C" &&
            p.PartType == PartType.Assembly
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_StatusAlwaysDraft()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Assembly, It.IsAny<CancellationToken>()))
            .ReturnsAsync("ASM-00001");

        var expectedResult = new PartDetailResponseModel(
            1, "ASM-00001", "Test", "A", PartStatus.Draft, PartType.Assembly,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            new List<BOMEntryResponseModel>(), new List<BOMUsageResponseModel>(),
            DateTime.UtcNow, DateTime.UtcNow);

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(expectedResult);

        var command = new CreatePartCommand("Test", null, PartType.Assembly, null, null, null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Status == PartStatus.Draft
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_TrimsWhitespace()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Part, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        var expectedResult = new PartDetailResponseModel(
            1, "PRT-00001", "Trimmed", "B", PartStatus.Draft, PartType.Part,
            "Steel", "M-100", null, null, null, null, null, null, null, null, null, null, null, null, null,
            new List<BOMEntryResponseModel>(), new List<BOMUsageResponseModel>(),
            DateTime.UtcNow, DateTime.UtcNow);

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(expectedResult);

        var command = new CreatePartCommand("  Trimmed  ", "  B  ", PartType.Part, "  Steel  ", "  M-100  ", null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.PartNumber == "PRT-00001" &&
            p.Description == "Trimmed" &&
            p.Revision == "B" &&
            p.Material == "Steel" &&
            p.MoldToolRef == "M-100"
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_WithExternalPartNumber_SetsField()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.RawMaterial, It.IsAny<CancellationToken>()))
            .ReturnsAsync("RAW-00001");

        var expectedResult = new PartDetailResponseModel(
            1, "RAW-00001", "Steel Bar", "A", PartStatus.Draft, PartType.RawMaterial,
            "Steel", null, "VENDOR-12345", null, null, null, null, null, null, null, null, null, null, null, null,
            new List<BOMEntryResponseModel>(), new List<BOMUsageResponseModel>(),
            DateTime.UtcNow, DateTime.UtcNow);

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(expectedResult);

        var command = new CreatePartCommand("Steel Bar", null, PartType.RawMaterial, "Steel", null, "  VENDOR-12345  ");

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.ExternalPartNumber == "VENDOR-12345"
        ), It.IsAny<CancellationToken>()), Times.Once);
    }
}
