namespace QBEngineer.Core.Models;

public record InvoiceDetailResponseModel(
    int Id,
    string InvoiceNumber,
    int CustomerId,
    string CustomerName,
    int? SalesOrderId,
    string? SalesOrderNumber,
    int? ShipmentId,
    string? ShipmentNumber,
    string Status,
    DateTime InvoiceDate,
    DateTime DueDate,
    string? CreditTerms,
    decimal TaxRate,
    decimal Subtotal,
    decimal TaxAmount,
    decimal Total,
    decimal AmountPaid,
    decimal BalanceDue,
    string? Notes,
    List<InvoiceLineResponseModel> Lines,
    List<PaymentApplicationResponseModel> PaymentApplications,
    DateTime CreatedAt,
    DateTime UpdatedAt);
